"""Utility methods for the project."""

import re


def reformat_sentence(text: str) -> str:
    """Clean up a sentence generated by OpenAI's GPT API."""
    # Remove non-letter characters from beginning of string
    text = re.sub(r"^[^a-zA-Z]*", "", text)

    # Remove extra white space around punctuation
    reformatted_text = re.sub(r"\s*([()'.,!?;:])(?!\.\s*\w)", r"\1", text)
    reformatted_text = re.sub(" +", " ", reformatted_text)

    # Remove extra white space around hyphens
    reformatted_text = re.sub(r"\s*-\s*", "-", reformatted_text)

    return reformatted_text


def valid_url(s: str) -> bool:
    """Check if a given string is a valid URL."""
    regex = re.compile(
        r"^(?:http|ftp)s?://"
        r"(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,63}|[A-Z]{2,63}\.[A-Z]{2,63}))"
        r"(?::\d+)?"
        r"(?:/?|[/?]\S+)$",
        re.IGNORECASE,
    )
    return bool(regex.match(s))
